version: '3.8'

services:
  oauth:
    image: "${IMAGE_TAG}"  # Ensure this environment variable is properly set
    ports:
      - "3001:3001"
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3