version: '3.8'

services:
  oauth:
    build: .
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 5s  # More frequent checks
      timeout: 2s
      retries: 5
      start_period: 10s

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

  tests:
    image: curlimages/curl:latest
    depends_on:
      oauth:
        condition: service_healthy
      db:
        condition: service_healthy
    command:
      - sh
      - -c
      - |
        echo "Waiting for services to be ready..."
        curl --retry 15 --retry-delay 2 --retry-connrefused http://oauth:3001/health
        echo "All services ready!"

volumes:
  pgdata: